# coding: utf-8

# flake8: noqa

# Copyright © 2020 Splunk, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"): you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# [http://www.apache.org/licenses/LICENSE-2.0]
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

############# This file is auto-generated.  Do not edit! #############

"""
    SDC Service: Ingest API

    Use the Ingest service in Splunk Cloud Services to send event and metrics data, or upload a static file, to Splunk Cloud Services.

    OpenAPI spec version: v1beta2.16 (recommended default)
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import apis into sdk package
from splunk_sdk.ingest.v1beta2.gen_ingest_api_api import IngestAPI

# import models into sdk package
from splunk_sdk.ingest.v1beta2.gen_models import Error, \
    Event, \
    FileUploadDetails, \
    HECResponse, \
    HECTokenAccessResponse, \
    HECTokenCreateRequest, \
    HECTokenCreateResponse, \
    HECTokenUpdateRequest, \
    HTTPResponse, \
    Metric, \
    MetricAttribute, \
    MetricEvent, \
    UploadSuccessResponse
