# coding: utf-8

# flake8: noqa

# Copyright © 2020 Splunk, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"): you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# [http://www.apache.org/licenses/LICENSE-2.0]
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

############# This file is auto-generated.  Do not edit! #############

"""
    SDC Service: App Registry

    With the App Registry service in Splunk Cloud Services, you can create, update, and manage your apps.

    OpenAPI spec version: v1beta2.0 (recommended default)
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import apis into sdk package
from splunk_sdk.app_registry.v1beta2.gen_app_registry_api import AppRegistry

# import models into sdk package
from splunk_sdk.app_registry.v1beta2.gen_models import AppName, \
    AppResourceKind, \
    AppResponseCreateUpdate, \
    AppResponseGetList, \
    CreateAppRequest, \
    Error, \
    Key, \
    NativeAppFromAppResponseCreateUpdate, \
    NativeAppFromAppResponseGetList, \
    NativeAppPOST, \
    ServiceAppFromAppResponseCreateUpdate, \
    ServiceAppFromAppResponseGetList, \
    ServiceAppPOST, \
    Subscription, \
    UpdateAppRequest, \
    WebAppFromAppResponseCreateUpdate, \
    WebAppFromAppResponseGetList
